// situacao-hotel — pacote a1-04
const { T, salva } = require('./comum');

const L1 = {
  id: 'situacao-hotel.na-imigracao-o-passaporte',
  trilha: 'situacao-hotel',
  nome: 'Na imigração: o passaporte',
  emoji: '🛂',
  cena: 'No aeroporto de Chicago, o oficial da imigração e depois o da alfândega fazem perguntas rápidas; você responde curto e com calma.',
  resumo: 'Respostas curtas na imigração: motivo da viagem, quanto tempo, onde fica e nada a declarar.',
  fechamento: false,
  novos: ["I'm here on business.", 'For five days.', 'At a hotel downtown.', 'Nothing to declare.'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Respostas curtas na imigração' },
    { t: 'p', c: 'O oficial pergunta rápido e espera resposta **curta**. As perguntas dele aparecem em cinza (você não digita): motivo, quanto tempo, onde vai ficar e se tem algo a declarar.' },
    { t: 'ex', c: "I'm here on business.\nEstou aqui a negócios." },
    { t: 'warn', c: "Estar aqui = **be** here. O I'm não pode sumir: I'm here on business (não: I here on business)." },
    { t: 'tip', c: '**downtown** = no centro da cidade, sem preposição antes: a hotel downtown.' },
  ],
  imagem: '🛂✈️🧳',
  visualizacao: 'Você está na fila da imigração em Chicago, passaporte na mão. O oficial levanta os olhos da tela e pergunta rápido; você respira e responde curto.',
  foto_busca: 'airport passport control booth',
  trechos: [
    {
      id: 'f-ef3e78', quem: 'voce', contexto: "What's the purpose of your visit?",
      cod: "I'm here on business.", dica: 'Estou aqui a negócios.', img: '💼✈️',
      alvo: 'here on business', alvo_pt: 'aqui a negócios',
      lit: '[lit.: eu estou aqui em negócios]',
      conceito: 'Estar aqui = be here; a negócios = on business.',
      registro: 'neutro', interferencias: ['BR04'], armadilhas: ['i', 'for'], teste: true,
      origem: 'tatoeba', fonte: T(2547741, 'CK', 4853103, 'Ricardo14'),
    },
    {
      id: 'f-231af0', quem: 'voce', contexto: 'How long are you staying?',
      cod: 'For five days.', dica: 'Por cinco dias.', img: '🗓️⏳',
      alvo: 'For five days', alvo_pt: 'Por cinco dias',
      conceito: 'Duração = for + tempo: for five days.',
      registro: 'neutro', armadilhas: ['during'], origem: 'autoral_ia',
    },
    {
      id: 'f-6026e8', quem: 'voce', contexto: 'Where are you staying?',
      cod: 'At a hotel downtown.', dica: 'Num hotel no centro.', img: '🏨🏙️',
      alvo: 'At a hotel downtown', alvo_pt: 'Num hotel no centro',
      conceito: 'downtown = no centro (da cidade); vem depois do lugar, sem preposição.',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-a1b920', quem: 'voce', contexto: 'Anything to declare?',
      cod: 'No, nothing to declare.', dica: 'Não, nada a declarar.', img: '🧳🚫',
      alvo: 'nothing to declare', alvo_pt: 'nada a declarar',
      conceito: 'declare = declarar (na alfândega).',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-a472ef', quem: 'voce', contexto: 'Are you here on vacation?',
      cod: 'No, on business. I work for an American company.',
      dica: 'Não, a negócios. Trabalho para uma empresa americana.', img: '💼🇺🇸',
      alvo: 'on business', alvo_pt: 'a negócios',
      conceito: 'I work for... = trabalho para... (o presente simples abre na próxima trilha).',
      registro: 'neutro', interferencias: ['BR15'], origem: 'autoral_ia', variacao_de: 'f-ef3e78',
    },
    {
      id: 'f-13a8d6', quem: 'voce', contexto: 'Are you staying with friends?',
      cod: 'No, at a hotel downtown. This is the address.',
      dica: 'Não, num hotel no centro. Este é o endereço.', img: '🏨📍',
      alvo: 'at a hotel downtown', alvo_pt: 'num hotel no centro',
      conceito: 'address = endereço (com dois d e dois s).',
      registro: 'neutro', origem: 'autoral_ia', variacao_de: 'f-6026e8',
    },
    {
      id: 'f-81edb3', quem: 'voce', contexto: 'How long are you in town?',
      cod: "I'm here for five days.", dica: 'Estou aqui por cinco dias.', img: '📅🧳',
      alvo: 'for five days', alvo_pt: 'por cinco dias',
      conceito: 'Por + tempo = for + tempo (nunca during five days).',
      registro: 'neutro', armadilhas: ['during'], origem: 'autoral_ia', variacao_de: 'f-231af0',
    },
    {
      id: 'f-e770b0', quem: 'voce', contexto: "What's in your bag?",
      cod: 'Just my laptop. Nothing to declare.', dica: 'Só o meu laptop. Nada a declarar.', img: '🎒💻',
      alvo: 'Nothing to declare', alvo_pt: 'Nada a declarar',
      conceito: 'just = só, apenas.',
      registro: 'neutro', origem: 'autoral_ia', variacao_de: 'f-a1b920',
    },
  ],
};

const L2 = {
  id: 'situacao-hotel.check-in-tenho-uma-reserva',
  trilha: 'situacao-hotel',
  nome: 'Check-in: tenho uma reserva',
  emoji: '🛎️',
  cena: 'À noite, logo depois do voo, você faz o check-in num hotel em Chicago, e a recepcionista não acha a sua reserva de primeira.',
  resumo: 'Fazer o check-in: dizer que tem reserva, dar o nome, as noites e o passaporte.',
  fechamento: false,
  novos: ['I have a reservation.', 'reservation', 'for three nights', 'passport'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Tenho uma reserva' },
    { t: 'p', c: 'No check-in, três falas resolvem: **I have a reservation** (tenho uma reserva), o seu nome e **for three nights** (para três noites).' },
    { t: 'ex', c: 'Good evening. I have a reservation.\nBoa noite. Tenho uma reserva.' },
    { t: 'tip', c: "Boa noite **ao chegar** = Good evening. Here's my passport = Aqui está o meu passaporte." },
    { t: 'warn', c: 'Nome, sobrenome e Brazil sempre com maiúscula em inglês.' },
  ],
  imagem: '🛎️🏨🔑',
  visualizacao: 'É noite e você chega do voo ao balcão do hotel, puxando a mala. A recepcionista sorri, digita no computador e franze a testa olhando a tela.',
  foto_busca: 'hotel reception desk check in',
  trechos: [
    {
      id: 'f-63efc6', quem: 'voce',
      cod: 'Good evening. I have a reservation.', dica: '(ao chegar) Boa noite. Tenho uma reserva.', img: '🛎️📋',
      alvo: 'I have a reservation', alvo_pt: 'Tenho uma reserva',
      conceito: 'Boa noite ao chegar = Good evening.',
      registro: 'neutro', teste: true,
      origem: 'tatoeba_adaptada',
      fonte: T(2546908, 'CK', 4815086, 'Ricardo14', { mod: true, nota: 'We → I e acrescentado Good evening. (EN e PT)' }),
    },
    {
      id: 'f-951147', quem: 'voce', contexto: "Sure. What's the name?",
      cod: '{nome} {sobrenome}, for three nights.', dica: '{nome} {sobrenome}, para três noites.', img: '🗓️🌙',
      alvo: 'for three nights', alvo_pt: 'para três noites',
      conceito: 'for + noites = para quantas noites é a reserva.',
      registro: 'neutro', interferencias: ['BR15'], bio: ['nome', 'sobrenome'], origem: 'autoral_ia',
    },
    {
      id: 'f-aa29ad', quem: 'voce', contexto: "Hmm, sorry. I don't see your name here.",
      cod: 'Sorry, but I have a reservation.', dica: 'Desculpa, mas eu tenho uma reserva.', img: '😟📋',
      alvo: 'I have a reservation', alvo_pt: 'eu tenho uma reserva',
      conceito: 'but = mas.',
      registro: 'neutro', origem: 'autoral_ia', variacao_de: 'f-63efc6',
    },
    {
      id: 'f-07b82f', quem: 'voce', contexto: 'OK. How do you spell your last name?',
      cod: "Here's my passport.", dica: 'Aqui está o meu passaporte.', img: '🛂🤝',
      alvo: 'passport', alvo_pt: 'passaporte',
      conceito: "Here's = Here is: aqui está.",
      registro: 'neutro', origem: 'tatoeba',
      fonte: T(2648130, 'CK', null, null, { nota: 'PT reescrito (Eis o meu → Aqui está o meu)' }),
    },
    {
      id: 'f-b0373f', quem: 'recepcionista', contexto: 'f-07b82f',
      cod: "Oh, here's your reservation!", dica: 'Ah, aqui está a sua reserva!', img: '💻✅',
      alvo: 'reservation', alvo_pt: 'reserva',
      conceito: 'your = seu/sua de você; dele é his, dela é her.',
      registro: 'neutro', interferencias: ['BR11'], origem: 'autoral_ia',
    },
    {
      id: 'f-50252d', quem: 'voce', contexto: 'f-b0373f',
      cod: "Great. It's for three nights, right?", dica: 'Ótimo. É para três noites, né?', img: '🌙❓',
      alvo: 'for three nights', alvo_pt: 'para três noites',
      conceito: 'right? no fim = né?',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-0446a8', quem: 'recepcionista', contexto: 'f-50252d',
      cod: "That's right. Your reservation is for three nights.", dica: 'Isso mesmo. A sua reserva é para três noites.', img: '👍📅',
      alvo: 'reservation', alvo_pt: 'reserva',
      registro: 'neutro', interferencias: ['BR11'], origem: 'autoral_ia',
    },
    {
      id: 'f-d33c8e', quem: 'recepcionista',
      cod: "Here's your passport and your key.", dica: 'Aqui está o seu passaporte e a sua chave.', img: '🛂🔑',
      alvo: 'passport', alvo_pt: 'passaporte',
      var: [{ em: 'and your key', aceita: ['and key'] }],
      conceito: 'key = chave. Seu/sua de você = your.',
      registro: 'neutro', interferencias: ['BR11'], origem: 'autoral_ia',
    },
  ],
};

const L3 = {
  id: 'situacao-hotel.o-quarto-o-cafe-e-o-wi-fi',
  trilha: 'situacao-hotel',
  nome: 'O quarto, o café e o Wi-Fi',
  emoji: '📶',
  cena: 'Na recepção, você pergunta a senha do Wi-Fi e o horário do café da manhã; no dia seguinte, a Ana pergunta a senha para você.',
  resumo: 'Perguntar a senha do Wi-Fi e o horário do café da manhã.',
  fechamento: false,
  novos: ['Wi-Fi', "What's the Wi-Fi password?", 'password', 'breakfast'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Wi-Fi e café da manhã' },
    { t: 'p', c: "Duas perguntas que todo hóspede faz: **What's the Wi-Fi password?** e **What time is breakfast?** Repare: breakfast vai sem artigo." },
    { t: 'ex', c: 'What time is breakfast?\nQue horas é o café da manhã?' },
    { t: 'warn', c: 'Café da manhã = **breakfast**. Coffee é só a bebida.' },
    { t: 'tip', c: 'from seven to ten = das sete às dez; on the fifth floor = no quinto andar.' },
  ],
  imagem: '📶🔑🥐',
  visualizacao: 'Você está no balcão da recepção, a mala ao lado e o celular sem sinal na mão. Atrás da recepcionista, uma placa mostra o horário do café da manhã.',
  foto_busca: 'hotel lobby front desk',
  trechos: [
    {
      id: 'f-a632d0', quem: 'voce',
      cod: "What's the Wi-Fi password?", dica: 'Qual é a senha do Wi-Fi?', img: '📶🔑',
      alvo: "What's the Wi-Fi password", alvo_pt: 'Qual é a senha do Wi-Fi',
      conceito: 'password = senha. A senha do Wi-Fi = the Wi-Fi password (a coisa vem antes).',
      registro: 'neutro', interferencias: ['BR08'], teste: true,
      origem: 'tatoeba', fonte: T(6063929, 'mailohilohi', 5902487, 'bill'),
    },
    {
      id: 'f-27a85d', quem: 'recepcionista', contexto: 'f-a632d0',
      cod: 'The password is your room number.', dica: 'A senha é o número do seu quarto.', img: '🔑🚪',
      alvo: 'password', alvo_pt: 'senha',
      conceito: 'room number = número do quarto: em inglês, quarto vem antes de número.',
      registro: 'neutro', interferencias: ['BR08'], origem: 'autoral_ia',
    },
  ],
};
L3.trechos.push(
  {
    id: 'f-d744e0', quem: 'voce', contexto: 'Your room is on the fifth floor.',
    cod: 'Is the Wi-Fi good on the fifth floor?', dica: 'O Wi-Fi é bom no quinto andar?', img: '📶🏢',
    alvo: 'Wi-Fi', alvo_pt: 'Wi-Fi',
    conceito: 'on the fifth floor = no quinto andar.',
    registro: 'neutro', origem: 'autoral_ia',
  },
  {
    id: 'f-f06fe3', quem: 'recepcionista', contexto: 'f-d744e0',
    cod: 'Yes, the Wi-Fi is really good.', dica: 'É, sim. O Wi-Fi é bem bom.', img: '👍📶',
    alvo: 'Wi-Fi', alvo_pt: 'Wi-Fi',
    conceito: 'really + adjetivo = bem + adjetivo.',
    registro: 'neutro', origem: 'autoral_ia',
  },
  {
    id: 'f-e415d5', quem: 'voce', contexto: 'f-f06fe3',
    cod: 'Great. And what time is breakfast?', dica: 'Ótimo. E que horas é o café da manhã?', img: '⏰🥐',
    alvo: 'breakfast', alvo_pt: 'café da manhã',
    conceito: 'What time is...? = que horas é...? (como em What time is it?)',
    registro: 'neutro', armadilhas: ['the'], origem: 'autoral_ia',
  },
  {
    id: 'f-23e155', quem: 'recepcionista', contexto: 'f-e415d5',
    cod: 'Breakfast is from seven to ten.', dica: 'O café da manhã é das sete às dez.', img: '🍳🕖',
    alvo: 'Breakfast', alvo_pt: 'café da manhã',
    conceito: 'from... to... = das... às... Breakfast vai sem the.',
    registro: 'neutro', armadilhas: ['the'], origem: 'autoral_ia',
  },
  {
    id: 'f-0100a6', quem: 'ana',
    cod: "{nome}, what's the Wi-Fi password?", dica: '{nome}, qual é a senha do Wi-Fi?', img: '📱❓',
    alvo: "what's the Wi-Fi password", alvo_pt: 'qual é a senha do Wi-Fi',
    registro: 'informal', bio: ['nome'], variacao_de: 'f-a632d0',
    origem: 'tatoeba_adaptada',
    fonte: T(6063929, 'mailohilohi', 5902487, 'bill', { mod: true, nota: 'acrescentado o vocativo {nome} no início (EN e PT)' }),
  },
  {
    id: 'f-f2ee08', quem: 'voce', contexto: 'f-0100a6',
    cod: "The password? It's your room number.", dica: 'A senha? É o número do seu quarto.', img: '📱🔑',
    alvo: 'password', alvo_pt: 'senha',
    conceito: "It's = it is: a frase em inglês precisa do it.",
    registro: 'informal', origem: 'autoral_ia', variacao_de: 'f-27a85d',
  },
);

const L4 = {
  id: 'situacao-hotel.probleminhas-no-quarto',
  trilha: 'situacao-hotel',
  nome: 'Probleminhas no quarto',
  emoji: '🧺',
  cena: 'Na primeira noite o quarto é barulhento; de manhã falta toalha e água quente; no último dia, você pede um táxi para o aeroporto.',
  resumo: 'Avisar de um problema simples, pedir mais uma coisa com another e agradecer a ajuda.',
  fechamento: false,
  novos: ['another', 'Another towel, please.', 'noisy', 'help'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Pequenos problemas no hotel' },
    { t: 'p', c: 'Para reclamar, **be + adjetivo**: My room is very noisy (meu quarto está muito barulhento). Para pedir mais uma coisa: **another** + coisa.' },
    { t: 'ex', c: 'Another towel, please.\nOutra toalha, por favor.' },
    { t: 'warn', c: 'O quarto novo = **the new room**: o adjetivo vem antes do substantivo.' },
    { t: 'tip', c: 'Thanks for your help = Obrigado pela ajuda.' },
  ],
  imagem: '🛏️🔊🧺',
  visualizacao: 'É tarde e o barulho da rua não deixa você dormir. Você desce de chinelo até a recepção; o saguão está vazio e o recepcionista levanta os olhos.',
  foto_busca: 'hotel room towels bed',
  trechos: [
    {
      id: 'f-c8b6f8', quem: 'voce',
      cod: 'Excuse me, my room is very noisy.', dica: 'Com licença, o meu quarto está muito barulhento.', img: '🛏️🔊',
      alvo: 'noisy', alvo_pt: 'barulhento',
      lit: '[lit.: meu quarto é muito barulhento]',
      conceito: 'Estar + adjetivo = be + adjetivo: my room is noisy.',
      registro: 'neutro', interferencias: ['BR04'], teste: true, origem: 'autoral_ia',
    },
    {
      id: 'f-517855', quem: 'recepcionista', contexto: 'f-c8b6f8',
      cod: "I'm sorry. Another room, on the fifth floor?", dica: 'Sinto muito. Outro quarto, no quinto andar?', img: '🔄🚪',
      alvo: 'Another', alvo_pt: 'Outro',
      conceito: 'another = outro, outra (mais um ou um diferente).',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-430232', quem: 'voce', contexto: 'f-517855',
      cod: 'Yes, please. Thanks for your help.', dica: 'Sim, por favor. Obrigado pela ajuda.',
      pt_f: 'Sim, por favor. Obrigada pela ajuda.', img: '🙏😊',
      alvo: 'help', alvo_pt: 'ajuda',
      var: [{ em: 'Thanks', aceita: ['Thank you'] }, { em: 'your help', aceita: ['the help'] }],
      conceito: 'Obrigado pela ajuda = Thanks for your help (for + coisa).',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-b69951', quem: 'voce', contexto: 'Front desk. Good morning!',
      cod: 'Good morning. Another towel, please.', dica: 'Bom dia. Outra toalha, por favor.', img: '🚿🧺',
      alvo: 'Another towel, please', alvo_pt: 'Outra toalha, por favor',
      conceito: 'towel = toalha.',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-d40b04', quem: 'voce', contexto: 'Sure.',
      cod: "And the new room isn't noisy. Thanks!", dica: 'E o quarto novo não está barulhento. Valeu!', img: '🤫🛏️',
      alvo: 'noisy', alvo_pt: 'barulhento',
      conceito: 'O quarto novo = the new room: o adjetivo vem antes.',
      registro: 'informal', interferencias: ['BR08', 'BR04'], origem: 'autoral_ia',
    },
    {
      id: 'f-f883fa', quem: 'voce',
      cod: 'I have another question. What time is checkout?', dica: 'Tenho outra pergunta. Que horas é o check-out?', img: '❓🕚',
      alvo: 'another', alvo_pt: 'outra',
      conceito: 'checkout = check-out, a hora de sair do hotel.',
      registro: 'neutro',
      origem: 'tatoeba_adaptada',
      fonte: T(1887358, 'CK', null, null, { mod: true, nota: 'acrescentada a pergunta What time is checkout?; PT reescrito' }),
    },
    {
      id: 'f-8f598f', quem: 'voce', contexto: 'Front desk. How can I help you?',
      cod: "There's no hot water. And another towel, please.", dica: 'Não tem água quente. E outra toalha, por favor.', img: '🚿🥶',
      alvo: 'another towel, please', alvo_pt: 'outra toalha, por favor',
      conceito: 'Não tem (está faltando) = there\'s no: there\'s no hot water.',
      registro: 'neutro', variacao_de: 'f-b69951',
      origem: 'tatoeba_adaptada',
      fonte: T(2217696, 'Hybrid', null, null, { mod: true, nota: 'acrescentado And another towel, please.; PT reescrito (Não há → Não tem)' }),
    },
    {
      id: 'f-35b96e', quem: 'voce', contexto: "Here's your receipt. Have a nice trip!",
      cod: 'A taxi to the airport, please. Thanks for your help!', dica: 'Um táxi para o aeroporto, por favor. Obrigado pela ajuda!',
      pt_f: 'Um táxi para o aeroporto, por favor. Obrigada pela ajuda!', img: '🚕✈️',
      alvo: 'help', alvo_pt: 'ajuda',
      var: [{ em: 'Thanks', aceita: ['Thank you'] }, { em: 'your help', aceita: ['the help'] }],
      conceito: 'A taxi to the airport = um táxi para o aeroporto.',
      registro: 'neutro', origem: 'autoral_ia', variacao_de: 'f-430232',
    },
  ],
};

salva('situacao-hotel', [L1, L2, L3, L4]);
