// presente-simples — pacote a1-04
const { T, salva } = require('./comum');
const TR = 'presente-simples';

const L1 = {
  id: 'presente-simples.trabalho-de-casa-moro-em-curitiba',
  trilha: TR,
  nome: 'Trabalho de casa, moro em Curitiba',
  emoji: '🏡',
  cena: 'Numa chamada de vídeo, o Mike quer saber como é a sua vida e o seu trabalho remoto no Brasil.',
  resumo: 'Dizer onde mora, como trabalha e que línguas fala com o presente simples: I work, I live, we speak.',
  fechamento: false,
  novos: ['work from home', 'live', 'live in', 'speak'],
  apoio: ['work', 'work for', 'company', 'have'],
  teoria: [
    { t: 'h', c: 'Presente simples: I work, I live' },
    { t: 'p', c: 'Para o que é sempre assim (trabalho, casa, rotina), o verbo vai **puro** depois de I, you, we e they: I work, we live, they speak.' },
    { t: 'ex', c: 'I work from home.\nEu trabalho de casa.' },
    { t: 'warn', c: 'Nunca junte be com outro verbo: I work (não: I am work).' },
    { t: 'tip', c: 'Morar em + cidade = **live in**: I live in Chicago. Línguas com maiúscula: Portuguese, English.' },
  ],
  imagem: '💻🏡🌎',
  visualizacao: 'Você está na mesa de casa, de fone, numa chamada de vídeo com o Mike. Atrás dele, a janela mostra os prédios de Chicago; atrás de você, a sua sala.',
  foto_busca: 'home office video call laptop',
  trechos: [
    {
      id: 'f-2a3122', quem: 'voce',
      cod: "I'm a developer. I work from home.", dica: 'Sou desenvolvedor. Trabalho de casa.',
      pt_f: 'Sou desenvolvedora. Trabalho de casa.', img: '💻🏡',
      alvo: 'work from home', alvo_pt: 'Trabalho de casa',
      conceito: 'work from home = trabalhar de casa (remoto). Com I, o verbo vai puro: I work.',
      registro: 'neutro', armadilhas: ['am'], teste: true, origem: 'autoral_ia',
    },
    {
      id: 'f-88d741', quem: 'mike', contexto: 'f-2a3122',
      cod: 'Nice! I work from home too.', dica: 'Que legal! Eu também trabalho de casa.', img: '🙌🏠',
      alvo: 'work from home', alvo_pt: 'trabalho de casa',
      var: [{ em: 'I work from home too', aceita: ['I also work from home'] }],
      conceito: 'too (também) fica no fim da frase.',
      registro: 'informal', origem: 'autoral_ia', variacao_de: 'f-2a3122',
    },
    {
      id: 'f-37e080', quem: 'voce',
      cod: 'I live in {cidade}, Brazil.', dica: 'Eu moro em {cidade}, no Brasil.', img: '🇧🇷🏙️',
      alvo: 'live in', alvo_pt: 'moro em',
      var: [{ em: 'Brazil', aceita: ['in Brazil'] }],
      conceito: 'Morar em = live in. Cidade, país: Curitiba, Brazil.',
      registro: 'neutro', interferencias: ['BR15'], bio: ['cidade'],
      origem: 'tatoeba_adaptada',
      fonte: T(10560938, 'shekitten', null, null, { mod: true, nota: 'Rio de Janeiro → {cidade}; PT reescrito' }),
    },
    {
      id: 'f-00d836', quem: 'mike', contexto: 'f-37e080',
      cod: 'I live downtown.', dica: 'Eu moro no centro.', img: '🏙️🏢',
      alvo: 'live', alvo_pt: 'moro',
      conceito: 'downtown = no centro, sem preposição: I live downtown.',
      registro: 'neutro', origem: 'tatoeba', fonte: T(5858165, 'CK', 6317091, 'bill'),
    },
    {
      id: 'f-5843cd', quem: 'voce', contexto: 'Do you speak Spanish in Brazil?',
      cod: 'No, we speak Portuguese.', dica: 'Não, a gente fala português.', img: '🗣️🇧🇷',
      alvo: 'speak', alvo_pt: 'fala',
      conceito: 'Línguas com maiúscula em inglês: Portuguese, Spanish, English.',
      registro: 'informal', interferencias: ['BR15'],
      origem: 'tatoeba_adaptada',
      fonte: T(4667249, 'CK', null, null, { mod: true, nota: 'French → Portuguese e acrescentado No,; PT reescrito' }),
    },
    {
      id: 'f-0fa624', quem: 'voce',
      cod: 'We speak English in our meetings.', dica: 'A gente fala inglês nas nossas reuniões.', img: '👥💬',
      alvo: 'speak', alvo_pt: 'fala',
      conceito: 'meeting = reunião; nossas reuniões = our meetings.',
      registro: 'informal', interferencias: ['BR15'], origem: 'autoral_ia',
    },
    {
      id: 'f-dc3b2e', quem: 'voce',
      cod: 'And I live in a big apartment.', dica: 'E eu moro num apartamento grande.', img: '🏢🛋️',
      alvo: 'live in', alvo_pt: 'moro num',
      conceito: 'Apartamento grande = big apartment: o adjetivo vem antes.',
      registro: 'neutro', interferencias: ['BR08'], origem: 'autoral_ia',
    },
    {
      id: 'f-505275', quem: 'mike', contexto: 'f-dc3b2e',
      cod: 'My family and I live in a house.', dica: 'Eu e a minha família moramos numa casa.', img: '👨‍👩‍👧🏡',
      alvo: 'live', alvo_pt: 'moramos',
      var: [{ em: 'My family and I', aceita: ['Me and my family'] }],
      conceito: 'Em inglês, a outra pessoa vem antes: my family and I.',
      registro: 'neutro', origem: 'autoral_ia',
    },
  ],
};

const L2 = {
  id: 'presente-simples.gosto-de-cafe-amo-pizza',
  trilha: TR,
  nome: 'Gosto de café, amo pizza',
  emoji: '☕',
  cena: 'No café da manhã do hotel em Chicago, a Ana, o Mike e você falam do que adoram e do que odeiam comer e beber.',
  resumo: 'Dizer o que você adora e o que odeia com love e hate + coisa.',
  fechamento: false,
  novos: ['love', 'hate', 'coffee', 'rice'],
  apoio: ['water'],
  teoria: [
    { t: 'h', c: 'Adoro, odeio' },
    { t: 'p', c: '**love** (adorar) e **hate** (odiar) vêm direto antes da coisa, sem preposição: I love coffee. I hate cold water.' },
    { t: 'ex', c: 'I love coffee.\nEu adoro café.' },
    { t: 'warn', c: 'Gostar DE = like, sem of: I like rice (não: I like of rice).' },
    { t: 'tip', c: 'Café frio = cold coffee: o adjetivo vem antes.' },
  ],
  imagem: '☕🍳🍚',
  visualizacao: 'Você está numa mesa do café da manhã do hotel, com uma xícara quente na mão. A Ana prova o café dela e faz careta; o Mike chega com um prato cheio.',
  foto_busca: 'hotel breakfast table coffee',
  trechos: [
    {
      id: 'f-79828f', quem: 'ana',
      cod: 'Coffee, {nome}?', dica: 'Café, {nome}?', img: '☕❓',
      alvo: 'Coffee', alvo_pt: 'Café',
      conceito: 'coffee = café, a bebida. Café da manhã é breakfast.',
      registro: 'informal', bio: ['nome'], origem: 'autoral_ia',
    },
    {
      id: 'f-a49d3f', quem: 'voce', contexto: 'f-79828f',
      cod: 'Yes, please! I love coffee.', dica: 'Sim, por favor! Eu adoro café.', img: '😍☕',
      alvo: 'love', alvo_pt: 'adoro',
      conceito: 'Adorar + coisa = love + coisa: I love coffee.',
      registro: 'neutro', armadilhas: ['of'], teste: true, origem: 'autoral_ia',
    },
    {
      id: 'f-b987d5', quem: 'ana',
      cod: 'This coffee is really cold.', dica: 'Esse café está bem frio.', img: '☕🥶',
      alvo: 'coffee', alvo_pt: 'café',
      conceito: 'really + adjetivo = bem + adjetivo.',
      registro: 'informal',
      origem: 'tatoeba_adaptada',
      fonte: T(3824344, 'CK', null, null, { mod: true, nota: 'good → cold; PT reescrito' }),
    },
    {
      id: 'f-d1bff9', quem: 'voce', contexto: 'f-b987d5',
      cod: 'Oh no. I hate cold coffee.', dica: 'Ah, não. Eu odeio café frio.', img: '😖☕',
      alvo: 'hate', alvo_pt: 'odeio',
      conceito: 'Café frio = cold coffee: o adjetivo vem antes do substantivo.',
      registro: 'informal', interferencias: ['BR08'], origem: 'autoral_ia',
    },
    {
      id: 'f-a30b1d', quem: 'voce', contexto: 'So what do people eat in Brazil?',
      cod: 'We love rice and beans.', dica: 'A gente adora arroz e feijão.', img: '🍚🇧🇷',
      alvo: 'rice', alvo_pt: 'arroz',
      conceito: 'rice and beans = arroz e feijão (na mesma ordem).',
      registro: 'informal', origem: 'autoral_ia',
    },
    {
      id: 'f-438f4c', quem: 'mike', contexto: 'f-a30b1d',
      cod: 'I like rice.', dica: 'Eu gosto de arroz.', img: '👍🍚',
      alvo: 'rice', alvo_pt: 'arroz',
      conceito: 'Gostar de = like, sem of.',
      registro: 'neutro', armadilhas: ['of'],
      origem: 'tatoeba', fonte: T(2807658, 'Hybrid', null, null, { nota: 'PT reescrito (Gosto de arroz. → Eu gosto de arroz.)' }),
    },
    {
      id: 'f-73f31f', quem: 'ana', contexto: 'Water?',
      cod: 'No, thanks. I hate cold water.', dica: 'Não, obrigada. Eu odeio água fria.', img: '💧🥶',
      alvo: 'hate', alvo_pt: 'odeio',
      conceito: 'Água fria = cold water. Obrigada: a Ana é mulher.',
      registro: 'neutro', interferencias: ['BR08'], origem: 'autoral_ia', variacao_de: 'f-d1bff9',
    },
    {
      id: 'f-8c981a', quem: 'mike',
      cod: 'I love Brazilian food.', dica: 'Eu adoro comida brasileira.', img: '😋🇧🇷',
      alvo: 'love', alvo_pt: 'adoro',
      conceito: 'Comida brasileira = Brazilian food: adjetivo antes e com maiúscula.',
      registro: 'neutro', interferencias: ['BR08', 'BR15'],
      origem: 'tatoeba_adaptada',
      fonte: T(953525, 'CK', 1047520, 'brauliobezerra', { mod: true, nota: 'Italian → Brazilian (EN e PT)' }),
    },
  ],
};

const L3 = {
  id: 'presente-simples.quero-aprender-want-to-need-to',
  trilha: TR,
  nome: 'Quero aprender: want to, need to',
  emoji: '🎯',
  cena: 'Na primeira semana em Chicago, você e a Ana conversam no escritório sobre o que querem aprender e o que precisam fazer hoje.',
  resumo: 'Dizer o que quer, precisa e gostaria de fazer: I want to, I need to, I\'d like to + verbo.',
  fechamento: false,
  novos: ['I want to...', 'I need to...', "I'd like to...", 'learn'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Quero, preciso, gostaria de' },
    { t: 'p', c: 'Querer, precisar e gostaria de + verbo levam **to** antes do verbo: I want to learn, I need to fix, I\'d like to work.' },
    { t: 'ex', c: 'I need to fix this bug today.\nPreciso corrigir esse bug hoje.' },
    { t: 'warn', c: 'Nunca for to: I need to go (não: I need for to go).' },
    { t: 'tip', c: "**I'd like to** é o jeito educado de querer. I'd = I would." },
  ],
  imagem: '🎯📚💻',
  visualizacao: 'Você e a Ana estão lado a lado no escritório de Chicago, com café e notebooks abertos. Na sua tela, um bug vermelho espera por você.',
  foto_busca: 'coworkers office laptops coffee',
  trechos: [
    {
      id: 'f-e9d588', quem: 'voce',
      cod: 'I want to learn English.', dica: 'Quero aprender inglês.', img: '🎯🗣️',
      alvo: 'I want to', alvo_pt: 'Quero',
      conceito: 'Querer + verbo = want to + verbo.',
      registro: 'neutro', interferencias: ['BR30'], armadilhas: ['for'], teste: true,
      origem: 'tatoeba_adaptada',
      fonte: T(4574678, 'CK', null, null, { mod: true, nota: 'guitar → English; PT reescrito' }),
    },
    {
      id: 'f-5c6af3', quem: 'ana', contexto: 'f-e9d588',
      cod: 'And I want to learn Flutter.', dica: 'E eu quero aprender Flutter.', img: '📱📚',
      alvo: 'learn', alvo_pt: 'aprender',
      conceito: 'learn = aprender.',
      registro: 'neutro', interferencias: ['BR30'], origem: 'autoral_ia', variacao_de: 'f-e9d588',
    },
    {
      id: 'f-10a3c7', quem: 'voce', contexto: 'f-5c6af3',
      cod: "Ana, I'd like to work with you.", dica: 'Ana, eu gostaria de trabalhar com você.', img: '🤝💻',
      alvo: "I'd like to", alvo_pt: 'eu gostaria de',
      conceito: "I'd like to = gostaria de (educado). I'd = I would.",
      registro: 'neutro', interferencias: ['BR30'], origem: 'autoral_ia',
    },
    {
      id: 'f-30db25', quem: 'ana', contexto: 'f-10a3c7',
      cod: "Great! I'd like to learn Flutter with you.", dica: 'Ótimo! Eu gostaria de aprender Flutter com você.', img: '📱🤓',
      alvo: "I'd like to", alvo_pt: 'Eu gostaria de',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-18d82b', quem: 'voce',
      cod: 'I need to fix this bug today.', dica: 'Preciso corrigir esse bug hoje.', img: '🐞🔧',
      alvo: 'I need to', alvo_pt: 'Preciso',
      conceito: 'Precisar + verbo = need to + verbo. fix = corrigir.',
      registro: 'neutro', interferencias: ['BR30'], armadilhas: ['for'], origem: 'autoral_ia',
    },
    {
      id: 'f-692269', quem: 'ana',
      cod: 'What time is it? I need to call Sarah.', dica: 'Que horas são? Preciso ligar para a Sarah.', img: '⏰📞',
      alvo: 'I need to', alvo_pt: 'Preciso',
      conceito: 'Ligar para alguém = call + pessoa, sem to.',
      registro: 'neutro', interferencias: ['BR30'], armadilhas: ['to'],
      origem: 'tatoeba_adaptada',
      fonte: T(2387579, 'CK', null, null, { mod: true, nota: 'Tom → Sarah e acrescentado What time is it?; PT reescrito (chamar → ligar para)' }),
    },
    {
      id: 'f-ff30f0', quem: 'voce', contexto: "Let's work late tonight!",
      cod: "Sorry, I don't want to work at night.", dica: 'Desculpa, não quero trabalhar à noite.', img: '🌙🙅',
      alvo: 'want to', alvo_pt: 'quero',
      conceito: 'Não quero = I don\'t want to: o don\'t vem antes do want.',
      registro: 'neutro', interferencias: ['BR07', 'BR30'],
      origem: 'tatoeba_adaptada',
      fonte: T(6013537, 'CK', 8547183, 'bill', { mod: true, nota: 'acrescentado Sorry, no início (EN e PT)' }),
    },
    {
      id: 'f-53e811', quem: 'voce',
      cod: 'Thanks, Ana. I learn a lot from you.', dica: 'Valeu, Ana. Eu aprendo muito com você.', img: '🙏📚',
      alvo: 'learn', alvo_pt: 'aprendo',
      var: [{ em: 'from you', aceita: ['with you'] }],
      conceito: 'Aprender com alguém = learn from someone.',
      registro: 'informal',
      origem: 'tatoeba_adaptada',
      fonte: T(2055335, 'Dejo', null, null, { mod: true, nota: 'my father → you e acrescentado Thanks, Ana.; PT reescrito' }),
    },
  ],
};

const L4 = {
  id: 'presente-simples.nao-como-carne-don-t',
  trilha: TR,
  nome: "Não como carne: don't",
  emoji: '🥗',
  cena: 'No jantar com o time em Chicago, cada um conta o que come e o que não come, e você pede a sua bebida.',
  resumo: "Dizer o que você não faz com don't + verbo: I don't eat meat. I don't drink milk.",
  fechamento: false,
  novos: ['eat', 'drink', 'meat', 'fish'],
  apoio: [],
  teoria: [
    { t: 'h', c: "Negativa: don't + verbo" },
    { t: 'p', c: "Para negar no presente simples, ponha **don't** antes do verbo: I don't eat meat. We don't drink soda." },
    { t: 'ex', c: "I don't eat red meat.\nEu não como carne vermelha." },
    { t: 'warn', c: "O não do português vira don't: I don't eat meat (não: I no eat meat)." },
    { t: 'tip', c: 'Tomar uma bebida = **drink**: tomo café = I drink coffee.' },
  ],
  imagem: '🍽️🥩🐟',
  visualizacao: 'Você está numa mesa comprida de restaurante em Chicago, com o time em volta. O garçom anota os pedidos, o Mike ri alto e a Sarah olha o cardápio.',
  foto_busca: 'team dinner restaurant table',
  trechos: [
    {
      id: 'f-020945', quem: 'voce', contexto: 'Something to drink?',
      cod: "Water, please. I don't drink soda.", dica: 'Água, por favor. Eu não tomo refrigerante.', img: '💧🚫',
      alvo: 'drink', alvo_pt: 'tomo',
      conceito: 'Tomar (bebida) = drink. Refrigerante = soda.',
      registro: 'neutro', interferencias: ['BR07'], armadilhas: ['no'], teste: true, origem: 'autoral_ia',
    },
    {
      id: 'f-e9641b', quem: 'sarah',
      cod: "I don't eat red meat.", dica: 'Eu não como carne vermelha.', img: '🚫🥩',
      alvo: 'eat', alvo_pt: 'como',
      conceito: 'Carne vermelha = red meat: o adjetivo vem antes.',
      registro: 'neutro', interferencias: ['BR07', 'BR08'], armadilhas: ['no'],
      origem: 'tatoeba', fonte: T(6273599, 'CK', 9707442, 'bill'),
    },
    {
      id: 'f-1699bb', quem: 'mike', contexto: 'f-e9641b',
      cod: 'Really? I love meat!', dica: 'Sério? Eu adoro carne!', img: '😋🥩',
      alvo: 'meat', alvo_pt: 'carne',
      conceito: 'meat = carne (a comida).',
      registro: 'informal', origem: 'autoral_ia',
    },
    {
      id: 'f-bb9adf', quem: 'sarah', contexto: 'f-1699bb',
      cod: 'But I eat fish.', dica: 'Mas eu como peixe.', img: '🐟👍',
      alvo: 'fish', alvo_pt: 'peixe',
      conceito: 'but = mas.',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-c02756', quem: 'mike', contexto: 'f-bb9adf',
      cod: "I don't eat fish.", dica: 'Eu não como peixe.', img: '🚫🐟',
      alvo: 'fish', alvo_pt: 'peixe',
      registro: 'neutro', interferencias: ['BR07'], armadilhas: ['no'],
      origem: 'tatoeba', fonte: T(5858616, 'CK', 5867843, 'ianna'),
    },
    {
      id: 'f-c840d5', quem: 'ana', contexto: 'And you, Ana?',
      cod: 'Me? I eat everything!', dica: 'Eu? Eu como de tudo!', img: '😄🍽️',
      alvo: 'eat', alvo_pt: 'como',
      conceito: 'Comer de tudo = eat everything.',
      registro: 'informal',
      origem: 'tatoeba_adaptada',
      fonte: T(2100009, 'AlanF_US', null, null, { mod: true, nota: 'acrescentado Me? no início; PT reescrito (como tudo → como de tudo)' }),
    },
    {
      id: 'f-179c8c', quem: 'mike',
      cod: 'This meat is really good.', dica: 'Essa carne está bem boa.', img: '🥩👌',
      alvo: 'meat', alvo_pt: 'carne',
      conceito: 'really good = bem bom, bem boa.',
      registro: 'informal',
      origem: 'tatoeba_adaptada',
      fonte: T(3824344, 'CK', null, null, { mod: true, nota: 'coffee → meat; PT reescrito' }),
    },
    {
      id: 'f-9982dd', quem: 'voce', contexto: 'Coffee? With milk?',
      cod: "Coffee, please. I don't drink milk.", dica: 'Café, por favor. Eu não tomo leite.', img: '☕🚫🥛',
      alvo: 'drink', alvo_pt: 'tomo',
      conceito: "Não tomo = I don't drink.",
      registro: 'neutro', interferencias: ['BR07'], armadilhas: ['no'], origem: 'autoral_ia', variacao_de: 'f-020945',
    },
  ],
};

const L5 = {
  id: 'presente-simples.vou-pra-casa-vou-dormir',
  trilha: TR,
  nome: 'Vou pra casa, vou dormir',
  emoji: '🌙',
  cena: 'Numa ligação com o Ben, seu amigo de Boston, vocês comparam a rotina: você trabalha de casa e ele vai para o escritório.',
  resumo: 'Contar a rotina com go to work, have lunch, at home e go to bed, sem artigo.',
  fechamento: false,
  novos: ['go to bed', 'go to work', 'at home', 'have lunch'],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Rotina sem artigo' },
    { t: 'p', c: 'Algumas expressões de rotina vão **sem the**: go to work, go to bed, at home. E almoçar é **have lunch**.' },
    { t: 'ex', c: 'I go to bed at ten.\nEu vou dormir às dez.' },
    { t: 'warn', c: 'Sem the: go to bed (não: go to the bed), at home (não: in the home).' },
    { t: 'tip', c: 'at + hora = às: at ten = às dez; at noon = ao meio-dia.' },
  ],
  imagem: '🏠🍽️🛏️',
  visualizacao: 'É fim de tarde e você está no sofá, falando com o Ben pelo celular. Ele conta do escritório em Boston; você já fechou o notebook e ouve a rua lá fora.',
  foto_busca: 'phone call living room evening',
  trechos: [
    {
      id: 'f-9f06ec', quem: 'ben',
      cod: "I'm at home today.", dica: 'Estou em casa hoje.', img: '🏠😌',
      alvo: 'at home', alvo_pt: 'em casa',
      conceito: 'Em casa = at home, sem the.',
      registro: 'neutro', interferencias: ['BR16'], armadilhas: ['in'],
      origem: 'tatoeba', fonte: T(5859511, 'CK', 7445362, 'Ricardo14'),
    },
    {
      id: 'f-5d8dd4', quem: 'voce', contexto: 'f-9f06ec',
      cod: "I don't go to work. I work from home.", dica: 'Eu não vou para o trabalho. Trabalho de casa.', img: '🚫🏢🏡',
      alvo: 'go to work', alvo_pt: 'vou para o trabalho',
      conceito: 'Ir para o trabalho = go to work, sem the.',
      registro: 'neutro', interferencias: ['BR16', 'BR07'], armadilhas: ['the'], teste: true, origem: 'autoral_ia',
    },
    {
      id: 'f-375984', quem: 'ben', contexto: 'f-5d8dd4',
      cod: 'Nice. I go to work at seven.', dica: 'Que legal. Eu vou para o trabalho às sete.', img: '🏢⏰',
      alvo: 'go to work', alvo_pt: 'vou para o trabalho',
      conceito: 'at + hora = às: at seven = às sete.',
      registro: 'informal', interferencias: ['BR16'], armadilhas: ['the'], origem: 'autoral_ia',
    },
    {
      id: 'f-d94ec1', quem: 'voce',
      cod: 'I have lunch at noon.', dica: 'Eu almoço ao meio-dia.', img: '🍽️🕛',
      alvo: 'have lunch', alvo_pt: 'almoço',
      lit: '[lit.: eu tenho almoço ao meio-dia]',
      conceito: 'Almoçar = have lunch (have aqui é comer, fazer a refeição).',
      registro: 'neutro', armadilhas: ['lunch'], origem: 'autoral_ia',
    },
    {
      id: 'f-50aa67', quem: 'ben', contexto: 'f-d94ec1',
      cod: 'Not me. I have lunch at my desk.', dica: 'Eu não. Eu almoço na minha mesa.', img: '🥪💻',
      alvo: 'have lunch', alvo_pt: 'almoço',
      conceito: 'Eu não (em resposta) = Not me.',
      registro: 'informal', origem: 'autoral_ia',
    },
    {
      id: 'f-8d1de9', quem: 'voce', contexto: 'f-50aa67',
      cod: 'My desk is at home!', dica: 'A minha mesa fica em casa!', img: '🏡🪑',
      alvo: 'at home', alvo_pt: 'em casa',
      conceito: 'Ficar (lugar) = be: my desk is at home.',
      registro: 'informal', interferencias: ['BR16'], armadilhas: ['in'], origem: 'autoral_ia',
    },
    {
      id: 'f-34ecd2', quem: 'voce',
      cod: 'And I go to bed late.', dica: 'E eu vou dormir tarde.', img: '🛏️🌙',
      alvo: 'go to bed', alvo_pt: 'vou dormir',
      lit: '[lit.: eu vou para a cama tarde]',
      conceito: 'Ir dormir = go to bed, sem the.',
      registro: 'neutro', interferencias: ['BR16'], armadilhas: ['the', 'sleep'], origem: 'autoral_ia',
    },
    {
      id: 'f-40e896', quem: 'ben', contexto: 'f-34ecd2',
      cod: 'Really? I go to bed at ten.', dica: 'Sério? Eu vou dormir às dez.', img: '😴🕙',
      alvo: 'go to bed', alvo_pt: 'vou dormir',
      registro: 'informal', interferencias: ['BR16'], armadilhas: ['the'],
      origem: 'tatoeba_adaptada',
      fonte: T(7856312, 'basilhan', 7857448, 'Ricardo14', { mod: true, nota: 'acrescentado Really? no início (EN e PT)' }),
    },
  ],
};

const L6 = {
  id: 'presente-simples.cena-meu-dia-de-trabalho-remoto',
  trilha: TR,
  nome: 'Cena: meu dia de trabalho remoto',
  emoji: '💻',
  cena: 'Num áudio, o Ben pergunta como é trabalhar de casa e você conta o seu dia, do almoço ao jantar.',
  resumo: "Juntar tudo da trilha: presente simples, don't, at home e o que você adora numa conversa com o Ben.",
  fechamento: true,
  novos: [],
  apoio: [],
  teoria: [
    { t: 'h', c: 'Revisão: o meu dia' },
    { t: 'p', c: "Verbo puro com I, we e they; **don't** para negar; at home, go to work e go to bed **sem the**." },
    { t: 'ex', c: "I don't drink soda, but I love juice.\nEu não tomo refrigerante, mas adoro suco." },
  ],
  imagem: '☕💻🌙',
  visualizacao: 'Você está na cozinha de casa, caneca de café na mão, gravando um áudio para o Ben. Pela janela, a sua cidade começa a acordar e o notebook já está aberto.',
  foto_busca: 'coffee mug kitchen laptop',
  trechos: [
    {
      id: 'f-771c26', quem: 'voce', contexto: "So what's a normal day for you?",
      cod: 'Well, I live in {cidade} and work from home.', dica: 'Bom, eu moro em {cidade} e trabalho de casa.', img: '🏙️💻',
      alvo: 'live in', alvo_pt: 'moro em',
      registro: 'neutro', bio: ['cidade'], origem: 'autoral_ia',
    },
    {
      id: 'f-c7e4da', quem: 'voce',
      cod: 'We have meetings in English.', dica: 'A gente tem reuniões em inglês.', img: '👥🗣️',
      alvo: 'have', alvo_pt: 'tem',
      conceito: 'Ter (reunião) = have: we have meetings.',
      registro: 'informal', interferencias: ['BR15'], origem: 'autoral_ia',
    },
    {
      id: 'f-fce874', quem: 'ben', contexto: 'f-c7e4da',
      cod: 'Oh, I hate meetings.', dica: 'Ah, eu odeio reuniões.', img: '😩📅',
      alvo: 'hate', alvo_pt: 'odeio',
      registro: 'informal', origem: 'autoral_ia',
    },
    {
      id: 'f-c19841', quem: 'voce', contexto: 'And lunch?',
      cod: 'At noon, I have rice and beans.', dica: 'Ao meio-dia, eu como arroz e feijão.', img: '🕛🍚',
      alvo: 'rice and beans', alvo_pt: 'arroz e feijão',
      var: [{ em: 'have', aceita: ['eat'] }],
      conceito: 'have + comida = comer: I have rice and beans.',
      registro: 'neutro', origem: 'autoral_ia',
    },
    {
      id: 'f-f7497f', quem: 'ben', contexto: 'f-c19841',
      cod: 'Rice and beans? I love rice and beans!', dica: 'Arroz e feijão? Eu adoro arroz e feijão!', img: '😍🍛',
      alvo: 'love', alvo_pt: 'adoro',
      conceito: 'O Ben morou dois anos no Brasil.',
      registro: 'informal', origem: 'autoral_ia',
    },
    {
      id: 'f-ab4516', quem: 'voce',
      cod: "I don't drink soda, but I love juice.", dica: 'Eu não tomo refrigerante, mas adoro suco.', img: '🧃👍',
      alvo: "don't drink", alvo_pt: 'não tomo',
      conceito: 'juice = suco.',
      registro: 'neutro', interferencias: ['BR07'], armadilhas: ['no'], origem: 'autoral_ia',
    },
    {
      id: 'f-8f60a0', quem: 'voce',
      cod: 'At eight, I have dinner at home.', dica: 'Às oito, eu janto em casa.', img: '🍽️🌙',
      alvo: 'at home', alvo_pt: 'em casa',
      conceito: 'Jantar = have dinner (como have lunch).',
      registro: 'neutro', interferencias: ['BR16'], origem: 'autoral_ia',
    },
    {
      id: 'f-6c3906', quem: 'voce',
      cod: 'I love my work.', dica: 'Eu adoro o meu trabalho.', img: '❤️💻',
      alvo: 'love', alvo_pt: 'adoro',
      registro: 'neutro',
      origem: 'tatoeba', fonte: T(2380214, 'CK', 5426429, 'bill'),
    },
  ],
};

salva(TR, [L1, L2, L3, L4, L5, L6]);
