import 'desafio.dart';

/// Banco autoral de desafios do Arcade.
///
/// Regras de qualidade:
///  - só UMA opção pode estar correta (distratores plausíveis, nunca ambíguos);
///  - todo trecho de lógica foi executado de verdade (`dart run`) e a saída
///    confere com a opção certa;
///  - `explica` ensina o porquê em 1–2 frases, em pt-BR.
const List<Desafio> bancoDesafios = [
  // ═══════════════ LÓGICA — nível 1 ═══════════════
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: 'var x = 5;\nvar y = 2;\nprint(x ~/ y);',
    opcoes: ['2', '2.5', '3'],
    certa: 0,
    explica: 'O operador ~/ é a divisão INTEIRA: 5 ~/ 2 corta a parte decimal e dá 2.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "print('dart'.toUpperCase());",
    opcoes: ['DART', 'Dart', 'dart'],
    certa: 0,
    explica: 'toUpperCase() devolve o texto inteiro em MAIÚSCULAS.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "var nome = 'Ana';\nprint('Oi, \$nome!');",
    opcoes: ['Oi, Ana!', r'Oi, $nome!', 'Oi, nome!'],
    certa: 0,
    explica: r'O $ dentro da string interpola: $nome vira o VALOR da variável.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "var lista = [1, 2, 3];\nprint(lista.length);",
    opcoes: ['3', '2', '[1, 2, 3]'],
    certa: 0,
    explica: 'length conta os ELEMENTOS da lista — aqui são 3.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: 'print(10 % 3);',
    opcoes: ['1', '3', '0'],
    certa: 0,
    explica: 'O % devolve o RESTO da divisão: 10 ÷ 3 = 3, sobra 1.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: 'var a = 3;\na += 2;\nprint(a);',
    opcoes: ['5', '3', '32'],
    certa: 0,
    explica: 'a += 2 é atalho para a = a + 2 → 3 + 2 = 5.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "print('2' + '3');",
    opcoes: ['23', '5', 'erro'],
    certa: 0,
    explica: "Entre aspas é TEXTO: + junta as strings ('2' + '3' = '23'), não soma números.",
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "var frutas = ['uva', 'kiwi'];\nfrutas.add('figo');\nprint(frutas[2]);",
    opcoes: ['figo', 'kiwi', 'uva'],
    certa: 0,
    explica: 'O índice começa em 0: depois do add, a posição 2 é o figo.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: 'print(7 > 3 && 2 > 5);',
    opcoes: ['false', 'true', 'erro'],
    certa: 0,
    explica: 'O && exige os DOIS lados verdadeiros; 2 > 5 é falso, então o resultado é false.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 1,
    pergunta: 'O que aparece no console?',
    codigo: "var x = 10;\nprint(x > 5 ? 'alto' : 'baixo');",
    opcoes: ['alto', 'baixo', 'true'],
    certa: 0,
    explica: 'O operador ternário escolhe: condição verdadeira → primeiro valor (alto).',
  ),

  // ═══════════════ LÓGICA — nível 2 ═══════════════
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'var soma = 0;\nfor (var i = 1; i <= 3; i++) {\n  soma += i;\n}\nprint(soma);',
    opcoes: ['6', '3', '10'],
    certa: 0,
    explica: 'O laço soma 1 + 2 + 3 = 6 (o i vai até 3, incluso).',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'var n = 4;\nwhile (n > 1) {\n  n ~/= 2;\n}\nprint(n);',
    opcoes: ['1', '2', '0'],
    certa: 0,
    explica: 'n vai caindo pela metade (4 → 2 → 1) e o while para quando n chega a 1.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'var lista = [1, 2, 3, 4];\nprint(lista.where((n) => n.isEven).length);',
    opcoes: ['2', '4', '[2, 4]'],
    certa: 0,
    explica: 'where filtra os pares (2 e 4) e length conta: 2 elementos.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'var dobro = [for (var n in [1, 2, 3]) n * 2];\nprint(dobro);',
    opcoes: ['[2, 4, 6]', '[1, 2, 3]', '[2, 3, 4]'],
    certa: 0,
    explica: 'É uma collection-for: monta a lista nova multiplicando cada item por 2.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: "String? nome;\nprint(nome ?? 'anônimo');",
    opcoes: ['anônimo', 'null', 'nome'],
    certa: 0,
    explica: 'O ?? usa o valor da direita quando a esquerda é null.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: "var mapa = {'a': 1, 'b': 2};\nprint(mapa['c'] ?? 0);",
    opcoes: ['0', 'null', '2'],
    certa: 0,
    explica: "A chave 'c' não existe → mapa['c'] é null → o ?? devolve 0.",
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'int dobra(int n) => n * 2;\nprint(dobra(dobra(3)));',
    opcoes: ['12', '6', '9'],
    certa: 0,
    explica: 'De dentro pra fora: dobra(3) = 6, depois dobra(6) = 12.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: "var s = 'banana';\nprint(s.split('a').length);",
    opcoes: ['4', '3', '6'],
    certa: 0,
    explica: "Cortando 'banana' em cada 'a' sobram 4 pedaços: 'b', 'n', 'n' e '' (vazio no fim).",
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: 'var nums = [5, 1, 4];\nnums.sort();\nprint(nums.first);',
    opcoes: ['1', '5', '4'],
    certa: 0,
    explica: 'sort() ordena crescente ([1, 4, 5]) e first pega o primeiro: 1.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 2,
    pergunta: 'O que aparece no console?',
    codigo: "var x = 0;\nif (x != 0) {\n  print('tem');\n} else {\n  print('zero');\n}",
    opcoes: ['zero', 'tem', 'nada'],
    certa: 0,
    explica: 'x != 0 é falso (x É zero), então cai no else.',
  ),

  // ═══════════════ LÓGICA — nível 3 ═══════════════
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var nums = [1, 2, 3];\nvar total = nums.fold(10, (a, b) => a + b);\nprint(total);',
    opcoes: ['16', '6', '10'],
    certa: 0,
    explica: 'fold começa em 10 e vai somando cada item: 10 + 1 + 2 + 3 = 16.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var a = [1, 2];\nvar b = [0, ...a];\nprint(b);',
    opcoes: ['[0, 1, 2]', '[0, [1, 2]]', '[1, 2, 0]'],
    certa: 0,
    explica: 'O spread (...) despeja os itens de a DENTRO da lista nova, na posição.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: "print([1, 2, 3].map((n) => n * n).join('-'));",
    opcoes: ['1-4-9', '1-2-3', '149'],
    certa: 0,
    explica: "map eleva ao quadrado (1, 4, 9) e join('-') junta com traços.",
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo:
        "class Pessoa {\n  String nome;\n  Pessoa(this.nome);\n}\nvar p = Pessoa('Lia');\np.nome = 'Bia';\nprint(p.nome);",
    opcoes: ['Bia', 'Lia', 'erro'],
    certa: 0,
    explica: 'O campo nome não é final: a atribuição troca o valor para Bia.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var f = (int n) => n + 1;\nprint(f(f(1)));',
    opcoes: ['3', '2', '1'],
    certa: 0,
    explica: 'A função soma 1 duas vezes: f(1) = 2 e f(2) = 3.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: "Future<String> busca() async => 'dados';\nprint(await busca());",
    opcoes: ['dados', 'Future<String>', 'null'],
    certa: 0,
    explica: 'O await ESPERA o Future terminar e entrega o valor de dentro dele.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var conjunto = {1, 2, 2, 3};\nprint(conjunto.length);',
    opcoes: ['3', '4', '2'],
    certa: 0,
    explica: 'Set não repete: o segundo 2 é ignorado, sobram {1, 2, 3}.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: "var texto = 'dart';\nprint(texto.substring(1, 3));",
    opcoes: ['ar', 'art', 'da'],
    certa: 0,
    explica: 'substring(1, 3) pega dos índices 1 e 2 (o 3 fica de fora): "a" e "r".',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var lista = [3, 1]..add(2)..sort();\nprint(lista);',
    opcoes: ['[1, 2, 3]', '[3, 1, 2]', '[3, 1]'],
    certa: 0,
    explica: 'O cascade (..) chama add e sort NO MESMO objeto antes de guardar.',
  ),
  Desafio(
    tipo: TipoDesafio.logica,
    nivel: 3,
    pergunta: 'O que aparece no console?',
    codigo: 'var par = [1, 2, 3].firstWhere((n) => n.isEven);\nprint(par);',
    opcoes: ['2', '1', '[2]'],
    certa: 0,
    explica: 'firstWhere devolve o PRIMEIRO item que passa no teste — o primeiro par é 2.',
  ),

  // ═══════════════ SINTAXE — nível 1 ═══════════════
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Complete para criar uma constante conhecida já na compilação:',
    codigo: "___ pi = 3.14;",
    opcoes: ['const', 'var', 'dynamic'],
    certa: 0,
    explica: 'const congela o valor em tempo de COMPILAÇÃO; var deixa trocar depois.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Feche o bloco do main:',
    codigo: "void main() {\n  print('Olá');\n___",
    opcoes: ['}', ');', 'end'],
    certa: 0,
    explica: 'Todo { aberto fecha com } — em Dart não existe "end".',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Quem tem 18 anos OU MAIS é maior de idade. Complete:',
    codigo: "var idade = 18;\nif (idade ___ 18) {\n  print('maior de idade');\n}",
    opcoes: ['>=', '>', '=='],
    certa: 0,
    explica: 'O >= inclui o próprio 18; só > deixaria os de exatamente 18 de fora.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Abra a lista de compras:',
    codigo: "var itens = ___ 'pão', 'leite' ];",
    opcoes: ['[', '{', '('],
    certa: 0,
    explica: 'Lista usa colchetes [ ]; chaves { } criam Set ou Map.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Mostre o ANO dentro do texto (interpolação):',
    codigo: "var ano = 2026;\nprint('Estamos em ___');",
    opcoes: [r'$ano', 'ano', '{ano}'],
    certa: 0,
    explica: r'Dentro de aspas, $variavel injeta o valor; sem o $ vira texto comum.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Repita 3 vezes. Qual palavra abre o laço?',
    codigo: '___ (var i = 0; i < 3; i++) {\n  print(i);\n}',
    opcoes: ['for', 'loop', 'repeat'],
    certa: 0,
    explica: 'O laço com contador em Dart é o for (início; condição; passo).',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Devolva o resultado da função:',
    codigo: 'int soma(int a, int b) {\n  ___ a + b;\n}',
    opcoes: ['return', 'print', 'yield'],
    certa: 0,
    explica: 'return entrega o valor a quem chamou; print só mostra no console.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Complete com o valor booleano VERDADEIRO:',
    codigo: 'var ligado = ___;',
    opcoes: ['true', "'true'", '1'],
    certa: 0,
    explica: "Booleano é true/false sem aspas — 'true' é texto e 1 é número.",
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Transforme numa função de UMA expressão (corpo curto):',
    codigo: "String saudacao() ___ 'Oi!';",
    opcoes: ['=>', '=', ':'],
    certa: 0,
    explica: 'A arrow function (=>) devolve a expressão direto, sem chaves nem return.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 1,
    pergunta: 'Qual tipo declara um número COM vírgula?',
    codigo: '___ preco = 9.90;',
    opcoes: ['double', 'int', 'String'],
    certa: 0,
    explica: 'double guarda casas decimais; int é só para inteiros.',
  ),

  // ═══════════════ SINTAXE — nível 2 ═══════════════
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Complete o switch:',
    codigo: "var nota = 8;\nswitch (nota) {\n  ___ 8:\n    print('ótimo');\n}",
    opcoes: ['case', 'when', 'if'],
    certa: 0,
    explica: 'Cada ramo do switch começa com case valor:.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Capture o erro para o app não quebrar:',
    codigo: "try {\n  arriscado();\n} ___ (e) {\n  print('deu ruim');\n}",
    opcoes: ['catch', 'rescue', 'except'],
    certa: 0,
    explica: 'Em Dart o par é try/catch — rescue é Ruby, except é Python.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Use o valor reserva quando apelido for nulo:',
    codigo: "String? apelido;\nvar nome = apelido ___ 'sem nome';",
    opcoes: ['??', '||', '?:'],
    certa: 0,
    explica: 'O ?? é o operador de "se for null, usa este outro valor".',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Percorra cada fruta da lista:',
    codigo: 'for (var fruta ___ frutas) {\n  print(fruta);\n}',
    opcoes: ['in', 'of', ':'],
    certa: 0,
    explica: 'O for-in percorre coleções em Dart (of é JavaScript).',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Complete a função anônima do map:',
    codigo: 'var dobro = numeros.map((n) ___ n * 2);',
    opcoes: ['=>', '->', ':'],
    certa: 0,
    explica: 'Em Dart a seta da arrow function é => (o -> é de outras linguagens).',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Imprima o tamanho SEM quebrar se o nome for nulo:',
    codigo: 'String? nome;\nprint(nome___length);',
    opcoes: ['?.', '..', '!.'],
    certa: 0,
    explica: 'O ?. só acessa se não for null (devolve null em vez de quebrar); o !. quebraria.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Gato HERDA tudo de Animal. Complete:',
    codigo: 'class Gato ___ Animal {\n}',
    opcoes: ['extends', 'inherits', 'super'],
    certa: 0,
    explica: 'Herança em Dart usa extends; a subclasse ganha os membros da mãe.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Filtre SÓ os números pares:',
    codigo: 'var pares = [1, 2, 3, 4].___((n) => n.isEven);',
    opcoes: ['where', 'map', 'forEach'],
    certa: 0,
    explica: 'where filtra pelo teste; map transforma e forEach só percorre.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Marque a função que pode usar await:',
    codigo: 'void main() ___ {\n  var dado = await carrega();\n}',
    opcoes: ['async', 'await', 'future'],
    certa: 0,
    explica: 'Só funções marcadas com async podem usar await por dentro.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 2,
    pergunta: 'Corte o texto em pedaços na vírgula:',
    codigo: "var texto = 'a,b,c';\nvar partes = texto.___(',');",
    opcoes: ['split', 'join', 'trim'],
    certa: 0,
    explica: 'split corta em lista; join faz o contrário (cola); trim só tira espaços.',
  ),

  // ═══════════════ SINTAXE — nível 3 ═══════════════
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Espalhe a lista original dentro da cópia:',
    codigo: 'var copia = [___original];',
    opcoes: ['...', '..', '&'],
    certa: 0,
    explica: 'O spread (...) despeja cada item da outra lista aqui dentro.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Deixe o construtor utilizável em contexto const:',
    codigo: 'class Ponto {\n  final int x;\n  ___ Ponto(this.x);\n}',
    opcoes: ['const', 'static', 'final'],
    certa: 0,
    explica: 'Com campos final, o construtor const permite criar objetos imutáveis em compile-time.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Espere o atraso terminar antes de seguir:',
    codigo: 'Future<void> espera() async {\n  ___ Future.delayed(duracao);\n}',
    opcoes: ['await', 'async', 'then'],
    certa: 0,
    explica: 'await pausa a função até o Future completar.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Chame write SEM perder o buffer (cascade):',
    codigo: "var b = StringBuffer()___write('oi');",
    opcoes: ['..', '.', '?.'],
    certa: 0,
    explica: 'O cascade (..) chama o método e devolve o PRÓPRIO buffer; com . a variável receberia void.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Complete o Fibonacci recursivo:',
    codigo: 'int fib(int n) =>\n    n < 2 ? n : fib(n - 1) ___ fib(n - 2);',
    opcoes: ['+', '*', '-'],
    certa: 0,
    explica: 'Fibonacci SOMA os dois anteriores: fib(n-1) + fib(n-2).',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Dê ao Pato a habilidade do mixin Nadador:',
    codigo: 'mixin Nadador {\n}\nclass Pato ___ Nadador {\n}',
    opcoes: ['with', 'extends', 'has'],
    certa: 0,
    explica: 'Mixin entra na classe com with; extends é só para herança de classe.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Assine o contrato SEM herdar implementação:',
    codigo: 'abstract class Forma {\n  double area();\n}\nclass Circulo ___ Forma {\n}',
    opcoes: ['implements', 'with', 'imports'],
    certa: 0,
    explica: 'implements obriga a reescrever TODOS os métodos do contrato.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Transforme o resultado do map numa List de verdade:',
    codigo: 'var nomes = pessoas.map((p) => p.nome).___();',
    opcoes: ['toList', 'asList', 'list'],
    certa: 0,
    explica: 'map devolve um Iterable preguiçoso; toList() materializa a lista.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Teste se obj é uma String:',
    codigo: 'if (obj ___ String) {\n  print(obj.length);\n}',
    opcoes: ['is', 'as', '=='],
    certa: 0,
    explica: 'is testa o tipo (e ainda promove a variável dentro do if); as converte na marra.',
  ),
  Desafio(
    tipo: TipoDesafio.sintaxe,
    nivel: 3,
    pergunta: 'Passe o parâmetro NOMEADO nivel na chamada:',
    codigo: "void log(String msg, {int nivel = 1}) {}\nlog('oi', ___ 2);",
    opcoes: ['nivel:', 'nivel =', '@nivel'],
    certa: 0,
    explica: 'Parâmetro nomeado vai com dois-pontos na chamada: nivel: 2.',
  ),
];

/// Rodadas do Caça-Bug: cada trecho tem exatamente UMA linha defeituosa.
const List<DesafioBug> bancoBugs = [
  // ───────── nível 1 ─────────
  DesafioBug(
    nivel: 1,
    missao: 'Guardar o nome e mostrar no console',
    linhas: ["var nome = 'Ana'", 'print(nome);'],
    linhaComBug: 0,
    explica: 'Faltou o ; no fim da primeira linha — toda instrução termina com ponto e vírgula.',
  ),
  DesafioBug(
    nivel: 1,
    missao: 'Avisar quando x passar de 5',
    linhas: ['var x = 10;', 'if (x > 5) {', "  print('alto');", ']'],
    linhaComBug: 3,
    explica: 'O bloco abriu com { e tem que fechar com } — o ] é de lista.',
  ),
  DesafioBug(
    nivel: 1,
    missao: 'Comparar se a idade é exatamente 18',
    linhas: ['var idade = 20;', 'if (idade = 18) {', "  print('exatos 18');", '}'],
    linhaComBug: 1,
    explica: 'Um = só ATRIBUI; comparação usa == (dois iguais).',
  ),
  DesafioBug(
    nivel: 1,
    missao: 'Mostrar a última fruta da lista',
    linhas: ["var frutas = ['uva', 'kiwi'];", 'print(frutas[2]);'],
    linhaComBug: 1,
    explica: 'Os índices são 0 e 1 — frutas[2] não existe e estoura RangeError. A última é frutas[1].',
  ),
  DesafioBug(
    nivel: 1,
    missao: 'Acumular 5 no total',
    linhas: ['final total = 10;', 'total = total + 5;', 'print(total);'],
    linhaComBug: 1,
    explica: 'final não aceita novo valor depois de criado — para reatribuir, use var.',
  ),
  DesafioBug(
    nivel: 1,
    missao: 'Montar o mapa de pontos',
    linhas: ["var mapa = {'a': 1; 'b': 2};", "print(mapa['a']);"],
    linhaComBug: 0,
    explica: 'Os pares do mapa se separam com VÍRGULA, não com ponto e vírgula.',
  ),

  // ───────── nível 2 ─────────
  DesafioBug(
    nivel: 2,
    missao: 'Somar os números de 0 a 4',
    linhas: ['var soma = 0;', 'for (var i = 0; i < 5; i--) {', '  soma += i;', '}'],
    linhaComBug: 1,
    explica: 'Com i-- o contador só DIMINUI e nunca chega a 5: laço infinito. Era i++.',
  ),
  DesafioBug(
    nivel: 2,
    missao: 'Montar a saudação e devolver o texto',
    linhas: ['String saudacao(String nome) {', "  'Olá, \$nome!';", '}', "print(saudacao('Lia'));"],
    linhaComBug: 1,
    explica: 'A função promete devolver String mas ninguém devolve nada — faltou o return.',
  ),
  DesafioBug(
    nivel: 2,
    missao: 'Dobrar cada número da lista',
    linhas: ['var numeros = [1, 2, 3];', 'var dobro = numeros.map(n => n * 2);'],
    linhaComBug: 1,
    explica: 'Em Dart o parâmetro da arrow precisa de parênteses: (n) => n * 2.',
  ),
  DesafioBug(
    nivel: 2,
    missao: 'Dobrar o número 5 (resultado esperado: 10)',
    linhas: ["var n = '5';", 'var dobro = n * 2;', 'print(dobro);'],
    linhaComBug: 0,
    explica: "Com aspas, '5' é TEXTO — e texto * 2 repete ('55'). Sem aspas (ou com int.parse) daria 10.",
  ),
  DesafioBug(
    nivel: 2,
    missao: 'Guardar a fala com aspas dentro do texto',
    linhas: ['var texto = "Ela disse "oi" pra mim";', 'print(texto);'],
    linhaComBug: 0,
    explica: 'As aspas internas fecham a string antes da hora — use \'…"oi"…\' ou escape \\".',
  ),

  // ───────── nível 3 ─────────
  DesafioBug(
    nivel: 3,
    missao: 'Checar se a idade é par',
    linhas: ['int? idade;', 'print(idade.isEven);'],
    linhaComBug: 1,
    explica: 'idade pode ser null — o acesso seguro é idade?.isEven (ou garantir valor antes).',
  ),
  DesafioBug(
    nivel: 3,
    missao: 'Carregar os dados e medir o tamanho',
    linhas: [
      '// carregar() devolve Future<String>',
      'var dados = carregar();',
      'print(dados.length);',
    ],
    linhaComBug: 1,
    explica: 'Sem await, dados é um Future (e Future não tem length). Era: var dados = await carregar();',
  ),
  DesafioBug(
    nivel: 3,
    missao: 'Modelar um carro com cor',
    linhas: ['class Carro {', '  String cor;', '}'],
    linhaComBug: 1,
    explica: 'Campo não-nulo precisa nascer com valor: inicialize, peça no construtor ou marque late/String?.',
  ),
  DesafioBug(
    nivel: 3,
    missao: 'Acrescentar o 4 na lista',
    linhas: ['var lista = const [1, 2, 3];', 'lista.add(4);'],
    linhaComBug: 1,
    explica: 'Lista const é imutável — add() estoura erro em tempo de execução.',
  ),
  DesafioBug(
    nivel: 3,
    missao: 'Somar 2 + 3 com a função',
    linhas: ['int soma(int a, int b) {', '  return a + b;', '}', "print(soma(2, '3'));"],
    linhaComBug: 3,
    explica: "'3' entre aspas é String e o parâmetro pede int — tipos não batem.",
  ),
];
